<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EntPoint.Collector\EntPoint.Collector.csproj" />
    <ProjectReference Include="..\..\src\EntPoint.Core\EntPoint.Core.csproj" />
    <ProjectReference Include="..\..\src\EntPoint.Ingestion\EntPoint.Ingestion.csproj" />
    <ProjectReference Include="..\..\src\EntPoint.Persistence\EntPoint.Persistence.csproj" />
  </ItemGroup>

</Project>